@startuml manrembundle_diagram
:Client: as Client

rectangle "BundleTracker" as BT
'rectangle "BundleTrackerPrivate" as BTP
rectangle "TrackedBundle" as TB
'rectangle "BundleContext" as BC
rectangle "BundleAbstractTracked" as BAT
rectangle "BundleTrackerCustomizer" as BTC

Client -> BT : Remove()
BT -d- TB : Check open
BT -> BAT : Untrack()
TB <- BAT : CustomizerRemoved()
TB -d-> BTC : RemovedBundle()

note bottom of BAT : Removed Bundle from map\nIncrement count


@enduml
