@startuml
participant Client
participant ThreadPool
participant "Task1" as T1
participant "Task2" as T2
participant ConfigurationImpl
participant ConfigurationAdminImpl
participant Listeners

activate Client
Client -> ThreadPool : postTask()
activate ThreadPool
ThreadPool -> T1 : allocate()
activate T1
T1 -> ConfigurationImpl : Update()
activate ConfigurationImpl
ConfigurationImpl -> ConfigurationAdminImpl : NotifyConfigurationUpdated()
activate ConfigurationAdminImpl
ConfigurationAdminImpl -> ConfigurationAdminImpl : PerformAsync()
ConfigurationAdminImpl -> ThreadPool : postTask()
ThreadPool -> ConfigurationAdminImpl : return T2_future
ConfigurationAdminImpl -> ConfigurationImpl : return T2_future
deactivate ConfigurationAdminImpl
ConfigurationImpl -> T1 : return T2_future
deactivate ConfigurationImpl
T1 -> T2 : T2_future.get()

note over T1: Task1 waits forever\n for thread that will\n never be allocated

 
@enduml